### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by danalippmann** [Davisy/Detect-and-Translate-Text-Data#1]
Hi Davisy,
thanks for this interesting project I tried to translate a csv file and when using the little function def detect_and_translate I get following error:
Extra data: line 1 column 334 (char 333)

It works when the detected language is the same as the desired translation language. Could you help fixing it?
Thanks in advance

**Comment by Davisy** [comment]
Hello, @danalippmann can you share the screenshot of your code and the error message. Keep in mind that the function receives a text value, not a CSV file.

**Comment by danalippmann** [comment]
Thanks for your fast answer!
I know I tried first with a text value, but unfortunately it is not working either (see screenshort attached). It would also be possible to put a dataframe value in it ?

![image](https://user-images.githubusercontent.com/45237413/142009107-1d5e5bd2-1f33-4792-8402-9be14646137d.png)

**Comment by Davisy** [comment]
The problem is the package itself (google_trans_new) is not updated on the PyPI website.

Someone has opened an issue on the package GitHub repo and he posted a temporary alternative solution that you can try, please check it here https://github.com/lushan88a/google_trans_new/issues/45
